// <auto-generated />
using System;
using BirthdayBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BirthdayBot.Data.Migrations
{
    [DbContext(typeof(BotDatabaseContext))]
    [Migration("20251223082309_AddOnly")]
    partial class AddOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BirthdayBot.Data.GuildConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<bool>("AddOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("add_only");

                    b.Property<string>("AnnounceMessage")
                        .HasColumnType("text")
                        .HasColumnName("announce_message");

                    b.Property<string>("AnnounceMessagePl")
                        .HasColumnType("text")
                        .HasColumnName("announce_message_pl");

                    b.Property<bool>("AnnouncePing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("announce_ping");

                    b.Property<decimal?>("AnnouncementChannel")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("announcement_channel");

                    b.Property<decimal?>("BirthdayRole")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("birthday_role");

                    b.Property<bool>("EphemeralConfirm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ephemeral_confirm");

                    b.Property<string>("GuildTimeZone")
                        .HasColumnType("text")
                        .HasColumnName("guild_time_zone");

                    b.Property<DateTimeOffset>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId")
                        .HasName("pk_guild_configurations");

                    b.ToTable("guild_configurations", (string)null);
                });

            modelBuilder.Entity("BirthdayBot.Data.UserEntry", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<int>("BirthDay")
                        .HasColumnType("integer")
                        .HasColumnName("birth_day");

                    b.Property<int>("BirthMonth")
                        .HasColumnType("integer")
                        .HasColumnName("birth_month");

                    b.Property<DateTimeOffset>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_user_entries");

                    b.ToTable("user_entries", (string)null);
                });

            modelBuilder.Entity("BirthdayBot.Data.UserEntry", b =>
                {
                    b.HasOne("BirthdayBot.Data.GuildConfig", "Guild")
                        .WithMany("UserEntries")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_entries_guild_configurations_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("BirthdayBot.Data.GuildConfig", b =>
                {
                    b.Navigation("UserEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
