// <auto-generated />
using BirthdayBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BirthdayBot.Data.Migrations
{
    [DbContext(typeof(BotDatabaseContext))]
    [Migration("20260814051745_OptimizationsBranch")]
    partial class OptimizationsBranch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BirthdayBot.Data.GuildConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AddOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("AnnounceMessage")
                        .HasColumnType("text");

                    b.Property<string>("AnnounceMessagePl")
                        .HasColumnType("text");

                    b.Property<bool>("AnnouncePing")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("AnnouncementChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("BirthdayRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("EphemeralConfirm")
                        .HasColumnType("boolean");

                    b.Property<string>("GuildTimeZone")
                        .HasColumnType("text");

                    b.Property<LocalDate>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigurations");
                });

            modelBuilder.Entity("BirthdayBot.Data.UserEntry", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<LocalDate>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Instant>("LastProcessed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("UserEntries");
                });

            modelBuilder.Entity("NoiPublicBot.Common.UserCache.EFWarmCacheEntry", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("WarmCache");
                });

            modelBuilder.Entity("BirthdayBot.Data.UserEntry", b =>
                {
                    b.HasOne("BirthdayBot.Data.GuildConfig", "Guild")
                        .WithMany("UserEntries")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("BirthdayBot.Data.GuildConfig", b =>
                {
                    b.Navigation("UserEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
